/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hlr;

import com.ericsson.otp.erlang.*;
import com.iti.telecom.editor.BasicGraphEditor;
import com.mxgraph.model.mxCell;
import com.mxgraph.view.mxGraph;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class HLRForm extends javax.swing.JFrame {

    /**
     * Creates new form HLRForm
     */
    private DBhandler db;
    private IMSIForm iForm;
    private long imsiRangeE,imsiRangeS;
    private String hlrName,Nispc,Gt;
    com.iti.telecom.beans.HLR hlr;
    
    public HLRForm(com.iti.telecom.beans.HLR h) {
        
        iForm=new IMSIForm();
        initComponents();
        hlr=h;
       // setVerifiers();
        
        
        db=new DBhandler();
        db.startConnection();
        getHlrValues();
        System.out.println("end hlr form constructor ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NiTf = new javax.swing.JTextField();
        SpcTf = new javax.swing.JTextField();
        GtTf = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        GtTf1 = new javax.swing.JTextField();
        GtTf2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name:");

        nameTf.setColumns(7);
        nameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTfActionPerformed(evt);
            }
        });
        nameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTfFocusLost(evt);
            }
        });

        jLabel2.setText("NI-Spc");

        jLabel4.setText("GT:");

        NiTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NiTfActionPerformed(evt);
            }
        });
        NiTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NiTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NiTfFocusLost(evt);
            }
        });

        SpcTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                SpcTfFocusLost(evt);
            }
        });

        GtTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                GtTfFocusLost(evt);
            }
        });

        SubmitBtn.setText("Submit");
        SubmitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitBtnMouseClicked(evt);
            }
        });

        jButton1.setText("Set IMSI Range");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        GtTf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                GtTf1FocusLost(evt);
            }
        });

        GtTf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                GtTf2FocusLost(evt);
            }
        });

        jLabel5.setText("-");

        jLabel6.setText("-");

        jLabel7.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTf)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NiTf, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SpcTf, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GtTf, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GtTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GtTf2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel4))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubmitBtn)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NiTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpcTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(GtTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GtTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GtTf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(SubmitBtn))
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void NiTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NiTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NiTfActionPerformed

    private void SubmitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitBtnMouseClicked
        
        if(HlrExist(nameTf.getText())){
            if(checkFormat()){
                Gt=GtTf.getText()+GtTf1.getText()+GtTf2.getText();
                Nispc=NiTf.getText()+SpcTf.getText();
                System.out.println(Gt+" "+Nispc);
                try {
                    // TODO add your handling code here:
                    sendToErlang();

                } catch (SQLException ex) {
                    Logger.getLogger(HLRForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    hlrName=nameTf.getText();
                    StartFrame.setHlrName(hlrName);
                    createDB(hlrName,Nispc,Gt);
                } catch (SQLException ex) {
                    Logger.getLogger(HLRForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                imsiRangeS=iForm.getStart();
                imsiRangeE=iForm.getEnd();
                StartFrame.setHlrExist(true);
                this.setVisible(false);
                }
        }
        else
            JOptionPane.showMessageDialog(this,"hlr with this name is already exist in database");
    }//GEN-LAST:event_SubmitBtnMouseClicked
    private boolean HlrExist(String name) {
        ResultSet rs=null;
        rs=db.hlrExist(name);
        try {
            while(rs.next())
            {
                return false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(HLRForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            return true;
    }
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        iForm.setVisible(true);
        iForm.setSize(300,300);
    }//GEN-LAST:event_jButton1MouseClicked

    private void nameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTfFocusLost
        // TODO add your handling code here:
        if(!nameTf.getText().matches("[A-Z|a-z]([A-za-z0-9])*"))
            JOptionPane.showMessageDialog(this, "hlr name format is not correct");
    }//GEN-LAST:event_nameTfFocusLost

    private void NiTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NiTfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_NiTfFocusGained

    private void NiTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NiTfFocusLost
        // TODO add your handling code here:
        if(!NiTf.getText().matches("[0|2|3]"))
            JOptionPane.showMessageDialog(this, "ni should be 0,2, or 3");
    }//GEN-LAST:event_NiTfFocusLost

    private void SpcTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SpcTfFocusLost
        // TODO add your handling code here:
        if(Long.parseLong(SpcTf.getText())<0||Long.parseLong(SpcTf.getText())>16383)
            JOptionPane.showMessageDialog(this, "spc should be from 0 to 16383");
    }//GEN-LAST:event_SpcTfFocusLost

    private void GtTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GtTfFocusLost
        // TODO add your handling code here:
        if(!GtTf.getText().matches("[0-9]{2}"))
            JOptionPane.showMessageDialog(this, "first field of GT should be 2 digits");
            
        
    }//GEN-LAST:event_GtTfFocusLost

    private void GtTf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GtTf1FocusLost
        // TODO add your handling code here:
        if(!GtTf1.getText().matches("[0-9]{2}"))
            JOptionPane.showMessageDialog(this, "second field of GT should be 2 digits");
    }//GEN-LAST:event_GtTf1FocusLost

    private void GtTf2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GtTf2FocusLost
        // TODO add your handling code here:
        if(!GtTf2.getText().matches("[0-9]{10}"))
            JOptionPane.showMessageDialog(this, "third field of GT should be 10 digits");
    }//GEN-LAST:event_GtTf2FocusLost
    private void createDB(String name,String n,String g) throws SQLException
    {
        System.out.println("range "+iForm.getStart()+"  "+iForm.getEnd());
        db.createDB(name,iForm.getStartStr(),iForm.getEndStr(),n,g);
        submitData(name,iForm.getStartStr(),iForm.getEndStr(),n,g);
    }
    private void sendToErlang() throws SQLException
    {
        hlrName = nameTf.getText();
        String hlrSpc = Nispc;
        String hlrGt = Gt;

        OtpErlangObject[] obj1 = new OtpErlangObject[2];
        OtpErlangString ehlrname = new OtpErlangString (hlrName);
        OtpErlangAtom ehlrname1 = new OtpErlangAtom("hlr_name");
        obj1[1] = ehlrname;
        obj1[0] = ehlrname1;
        OtpErlangTuple t1 = new OtpErlangTuple(obj1);

        OtpErlangString ehlrspc = new OtpErlangString(hlrSpc);
        OtpErlangAtom ehlrspc1 = new OtpErlangAtom("spc");
        obj1[1] = ehlrspc;
        obj1[0] = ehlrspc1;
        OtpErlangTuple t2 = new OtpErlangTuple(obj1);

        OtpErlangString ehlrgt = new OtpErlangString (hlrGt);
        OtpErlangAtom ehlrgt1 = new OtpErlangAtom("gt");
        obj1[1] = ehlrgt;
        obj1[0] = ehlrgt1;
        OtpErlangTuple t3 = new OtpErlangTuple(obj1);

        OtpErlangObject[] obj2 = new OtpErlangObject[3];
        obj2[0] = t1;
        obj2[1] = t2;
        obj2[2] = t3;

        OtpErlangList l1 = new OtpErlangList(obj2);

                OtpErlangObject[] obj3 = new OtpErlangObject[1];
obj3[0] = l1;
try{
//sendtoerl2 sender = new sendtoerl2();////////////////////////
                com.iti.telecom.main.GraphEditor.sender.sendtoerl("newhlr", obj3);
}catch(Exception ex){}

    
    }

    public String getHlrName()
    {
        return hlrName;
    }
    public long getStartRange()
    {
        return imsiRangeS;
    }
    public long getendRange()
    {
        return imsiRangeE;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GtTf;
    private javax.swing.JTextField GtTf1;
    private javax.swing.JTextField GtTf2;
    private javax.swing.JTextField NiTf;
    private javax.swing.JTextField SpcTf;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameTf;
    // End of variables declaration//GEN-END:variables

    void setGtTf(String gt) {System.out.println("set gttf hlr form "+gt);
        if(gt.length()>7){
            GtTf.setText(gt.substring(0,2));
            GtTf1.setText(gt.substring(2,4));
            GtTf2.setText(gt.substring(4));
        }
        else
            GtTf.setText(gt);
        
    }

    void setNispcTf(String niSpc) {System.out.println("set nispctf hlr form "+niSpc);
        if(niSpc.length()>2){
            NiTf.setText(niSpc.substring(0,1));
            SpcTf.setText(niSpc.substring(1));
        }
        else
            NiTf.setText(niSpc);
    }

    void setHlrNameTf(String hlrName) {
        nameTf.setText(hlrName);
    }

    void setStartRangeTf(String startRange) {
        iForm.setStartTf(startRange);
    }

    void setEndRangeTf(String ENDRange) {
        iForm.setEndTf(ENDRange);
    }

    private boolean checkFormat() {
        if(!nameTf.getText().matches("[A-Z|a-z]([A-za-z0-9])*")){
            JOptionPane.showMessageDialog(this, "hlr name format is not correct");
            return false;
            }
        if(!NiTf.getText().matches("[0|2|3]")){
            JOptionPane.showMessageDialog(this, "ni should be 0,2, or 3");
            return false;
            }
        if(Long.parseLong(SpcTf.getText())<0||Long.parseLong(SpcTf.getText())>16383){
            JOptionPane.showMessageDialog(this, "spc should be from 0 to 16383");
            return false;
            }
        if(!GtTf.getText().matches("[0-9]{2}")){
            JOptionPane.showMessageDialog(this, "first field of GT should be 2 digits");
            return false;
            }
        if(!GtTf1.getText().matches("[0-9]{2}")){
            JOptionPane.showMessageDialog(this, "second field of GT should be 2 digits");
            return false;
            }
        if(!GtTf2.getText().matches("[0-9]{10}")){
            JOptionPane.showMessageDialog(this, "third field of GT should be 10 digits");
            return false;
            }
        
        return true;
    }

    private void getHlrValues() {
        nameTf.setText(hlr.getHlrName());
        System.out.println("get hlr values gt:"+hlr.getGt());
        System.out.println("nispc:"+hlr.getNiSpc());
        //iForm.setEndTf(hlr.getendRange());
        //iForm.setStartTf(hlr.getStartRange());
    }

    private void submitData(String name, String startStr, String endStr, String n, String g) {
        hlr.setHlrName(name);
        hlr.setStartRange(startStr);
        hlr.setendRange(endStr);
        hlr.setNiSpc(n);
        hlr.setGt(g);
    }

    


    
}
