/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Msc_Screen.java
 *
 * Created on Jun 10, 2012, 1:44:30 PM
 */
package msc;

import java.util.regex.Pattern;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Vendetta
 */
public class Msc_Screen extends javax.swing.JFrame {

    /** Creates new form Msc_Screen */
    public Msc_Screen() {
        initComponents();
        msc_name.setInputVerifier(new NameVerifier());

        NI_num.setInputVerifier(new NIVerifier());
        SPC_num.setInputVerifier(new SPCVerifier());

        gt1.setInputVerifier(new GT1Verifier());
        gt2.setInputVerifier(new GT2Verifier());
        gt3.setInputVerifier(new GT3Verifier());

        LA_id1.setInputVerifier(new LA1Verifier());
        LA_id2.setInputVerifier(new LA2Verifier());
        LA_id3.setInputVerifier(new LA3Verifier());

        VLR_add1.setInputVerifier(new VLR1Verifier());
        VLR_add2.setInputVerifier(new VLR2Verifier());
        VLR_add3.setInputVerifier(new VLR3Verifier());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Submit_comm = new javax.swing.JButton();
        NI_num = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gt1 = new javax.swing.JTextField();
        SPC_num = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LA_id1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        VLR_add1 = new javax.swing.JTextField();
        msc_name = new javax.swing.JTextField();
        gt_lbl = new javax.swing.JLabel();
        ni_lbl = new javax.swing.JLabel();
        vlr_lbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LA_id2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        LA_id3 = new javax.swing.JTextField();
        VLR_add2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        VLR_add3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        gt2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        gt3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        la_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Submit_comm.setText("Submit");
        Submit_comm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_commActionPerformed(evt);
            }
        });

        NI_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NI_numActionPerformed(evt);
            }
        });

        jLabel7.setText("-");

        SPC_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPC_numActionPerformed(evt);
            }
        });

        jLabel2.setText("VLR:");

        jLabel1.setBackground(new java.awt.Color(250, 254, 254));
        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(19, 7, 101));
        jLabel1.setText("MSC Conf");

        LA_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LA_id1ActionPerformed(evt);
            }
        });

        jLabel6.setText("GT:");

        jLabel5.setText("NI-SPC:");

        jLabel4.setText("LA:");

        jLabel3.setText("Name:");

        VLR_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VLR_add1ActionPerformed(evt);
            }
        });

        msc_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msc_nameActionPerformed(evt);
            }
        });

        gt_lbl.setForeground(new java.awt.Color(250, 65, 16));

        ni_lbl.setForeground(new java.awt.Color(250, 65, 16));

        vlr_lbl.setForeground(new java.awt.Color(250, 65, 16));

        jLabel11.setForeground(new java.awt.Color(250, 65, 16));

        name_lbl.setForeground(new java.awt.Color(250, 65, 16));

        jLabel8.setText("-");

        jLabel9.setText("-");

        LA_id3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LA_id3ActionPerformed(evt);
            }
        });

        jLabel10.setText("-");

        VLR_add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VLR_add3ActionPerformed(evt);
            }
        });

        jLabel12.setText("-");

        jLabel13.setText("-");

        gt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gt3ActionPerformed(evt);
            }
        });

        jLabel14.setText("-");

        la_lbl.setForeground(new java.awt.Color(251, 45, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NI_num, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(9, 9, 9)
                                .addComponent(gt2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gt3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SPC_num, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(vlr_lbl)
                            .addComponent(gt_lbl)
                            .addComponent(ni_lbl)
                            .addComponent(name_lbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(gt1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VLR_add1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LA_id1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(9, 9, 9)
                                .addComponent(LA_id2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LA_id3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(la_lbl))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(9, 9, 9)
                                .addComponent(VLR_add2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VLR_add3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(msc_name, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(457, Short.MAX_VALUE)
                .addComponent(Submit_comm)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(458, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(msc_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_lbl))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(SPC_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(NI_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ni_lbl))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(gt_lbl)
                    .addComponent(gt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(gt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(VLR_add1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vlr_lbl)
                    .addComponent(jLabel12)
                    .addComponent(VLR_add2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VLR_add3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(LA_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(LA_id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LA_id3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(la_lbl))
                .addGap(18, 18, 18)
                .addComponent(Submit_comm)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit_commActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_commActionPerformed

//        Writer output = null;
//        File file = new File(msc_name.getText()+".txt");
//        try {
//            output = new BufferedWriter(new FileWriter(file));
//        } catch (IOException ex) {
//            Logger.getLogger(Msc_Screen.class.getName()).log(Level.SEVERE, null, ex);
//        }

//        String text = "{name,\""+msc_name.getText()+"\"}\n"+"{NI-SPC,\""+NI_num.getText()+SPC_num.getText()+"\"}\n"
//                +"{GT,\""+gt.getText()+"\"}\n"+"{VLR,\""+VLR_add.getText()+"\"}\n"
//                +"{LA,\""+LA_id.getText()+"\"}\n";
        String NI_SPC = NI_num.getText() + SPC_num.getText();
        String GT = gt1.getText() + gt2.getText() + gt3.getText();
        String VLR = VLR_add1.getText() + VLR_add2.getText() + VLR_add3.getText();
        String LAI = LA_id1.getText() + LA_id2.getText() + LA_id3.getText();
        DatabaseHandler conn = new DatabaseHandler();
        conn.insert_msc_info(msc_name.getText(), NI_num.getText(), SPC_num.getText(), GT, VLR, LAI);
        msc_name.setText("");
        NI_num.setText("");
        SPC_num.setText("");
        gt1.setText("");
        gt2.setText("");
        gt3.setText("");
        VLR_add1.setText("");
        VLR_add2.setText("");
        VLR_add3.setText("");
        LA_id1.setText("");
        LA_id2.setText("");
        LA_id3.setText("");
//        try {
//            output.write(text);
//        } catch (IOException ex) {
//            Logger.getLogger(Msc_Screen.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        try {
//            output.close();
//        } catch (IOException ex) {
//            Logger.getLogger(Msc_Screen.class.getName()).log(Level.SEVERE, null, ex);
//        }
}//GEN-LAST:event_Submit_commActionPerformed

    private void NI_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NI_numActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_NI_numActionPerformed

    private void SPC_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPC_numActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_SPC_numActionPerformed

    private void LA_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LA_id1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_LA_id1ActionPerformed

    private void VLR_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VLR_add1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_VLR_add1ActionPerformed

    private void msc_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msc_nameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_msc_nameActionPerformed

    private void LA_id3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LA_id3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LA_id3ActionPerformed

    private void VLR_add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VLR_add3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VLR_add3ActionPerformed

    private void gt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gt3ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new Msc_Screen().setVisible(true);
//            }
//        });
//
//
//
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LA_id1;
    private javax.swing.JTextField LA_id2;
    private javax.swing.JTextField LA_id3;
    private javax.swing.JTextField NI_num;
    private javax.swing.JTextField SPC_num;
    private javax.swing.JButton Submit_comm;
    private javax.swing.JTextField VLR_add1;
    private javax.swing.JTextField VLR_add2;
    private javax.swing.JTextField VLR_add3;
    private javax.swing.JTextField gt1;
    private javax.swing.JTextField gt2;
    private javax.swing.JTextField gt3;
    private javax.swing.JLabel gt_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel la_lbl;
    private javax.swing.JTextField msc_name;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JLabel ni_lbl;
    private javax.swing.JLabel vlr_lbl;
    // End of variables declaration//GEN-END:variables

    public class NameVerifier extends InputVerifier {

        public boolean verify(JComponent input) {
            name_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();
            if (s.length() == 0) {
                //JOptionPane.showMessageDialog( null , "Name is empty ");
                //name_lbl.setVisible(true);
                name_lbl.setText("Name is empty");
                check = false;
            } else if (s.length() > 7) {
                JOptionPane.showMessageDialog(null, "Name must be less than 7 digits ");
                name_lbl.setText("1-7 digits are required");
                check = false;
            }

//        String path = ".";
//
//  String files;
//  File folder = new File(path);
//  File[] listOfFiles = folder.listFiles();
//
//  for (int i = 0; i < listOfFiles.length; i++)
//  {
//
//   if (listOfFiles[i].isFile() && listOfFiles[i].getName().equals(msc_name.getText()+".txt"))
//   {
//   JOptionPane.showMessageDialog( null , "MSC already exists!!");
//   check=false;
//      }
//  }
            //name_lbl.setText("");
            return check;
        }
    }

    public class NIVerifier extends InputVerifier {

        public boolean verify(JComponent input) {
            ni_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                ni_lbl.setText("NI isn't numeric");
                check = false;
            }
            if (s.length() == 0) {
                //JOptionPane.showMessageDialog( null , "Name is empty ");
                ni_lbl.setText("NI is empty");
                check = false;
            } else if (s.length() > 3) {
                //JOptionPane.showMessageDialog( null , "Name must be less than 3 digits ");
                ni_lbl.setText("1-3 digits are required");
                check = false;
            }
            return check;
        }
    }

    public class SPCVerifier extends InputVerifier {

        public boolean verify(JComponent input) {
            ni_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();
            if (!Pattern.matches("\\d*$", s)) {
                ni_lbl.setText("SPC isn't numeric");
                check = false;
            }
            if (s.length() == 0) {
                //JOptionPane.showMessageDialog( null , "Name is empty ");
                ni_lbl.setText("SPC is empty");
                check = false;
            } else if (s.length() > 14) {
                //JOptionPane.showMessageDialog( null , "Name must be less than 14 digits ");
                ni_lbl.setText("1-14 digits are required");
                check = false;
            }
            return check;
        }
    }

    public class GT1Verifier extends InputVerifier {

        public boolean verify(JComponent input) {
            gt_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                gt_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() != 3) {
                gt_lbl.setText("must be 3 digits");
                check = false;
            }
            return check;
        }
    }

    public class GT2Verifier extends InputVerifier {

        public boolean verify(JComponent input) {
            gt_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                gt_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() != 2) {
                gt_lbl.setText("must be 2 digits");
                check = false;
            }
            return check;
        }
    }

    public class GT3Verifier extends InputVerifier {

        public boolean verify(JComponent input) {
            gt_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                gt_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() != 10) {
                gt_lbl.setText("must be 10 digits");
                check = false;
            }
            return check;
        }
    }

    public class LA1Verifier extends InputVerifier {

        public boolean verify(JComponent input) {
            la_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                la_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() != 3) {
                la_lbl.setText("must be 3 digits");
                check = false;
            }
            return check;
        }
    }

    public class LA2Verifier extends InputVerifier {

        public boolean verify(JComponent input) {
            la_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                la_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() != 2) {
                la_lbl.setText("must be 2 digits");
                check = false;
            }
            return check;
        }
    }

    public class LA3Verifier extends InputVerifier {

        public boolean verify(JComponent input) {
            la_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                la_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() != 10) {
                la_lbl.setText("must be 10 digits");
                check = false;
            }
            return check;
        }
    }

    public class VLR1Verifier extends InputVerifier {

        public boolean verify(JComponent input) {
            vlr_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                vlr_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() != 3) {
                vlr_lbl.setText("must be 3 digits");
                check = false;
            }
            return check;
        }
    }

    public class VLR2Verifier extends InputVerifier {

        public boolean verify(JComponent input) {
            vlr_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                vlr_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() != 2) {
                vlr_lbl.setText("must be 2 digits");
                check = false;
            }
            return check;
        }
    }

    public class VLR3Verifier extends InputVerifier {

        public boolean verify(JComponent input) {
            vlr_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                vlr_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() != 10) {
                vlr_lbl.setText("must be 10 digits");
                check = false;
            }
            return check;
        }
    }
}
