/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * msrn_range.java
 *
 * Created on Jun 23, 2012, 12:00:14 PM
 */

package msc;

import java.util.regex.Pattern;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JTextField;
//import sun.org.mozilla.javascript.regexp.SubString;

/**
 *
 * @author Vendetta
 */
public class msrn_range extends javax.swing.JFrame {


    public static DatabaseHandler dbh;
    public String MSCName ;
    public String MSRNNumber;
    public int msrn_no;
    public String MSRN;
    public String CC;
    public String NDC;
    public String SN;
    /** Creates new form msrn_range */
    public msrn_range(String msc_name) {
        initComponents();
        try{
        dbh = new DatabaseHandler();
        MSCName=msc_name;
   //     MSRNNumber=dbh.get_msrn_no();
   //     CC = MSRNNumber.substring(0, 2);
   //     NDC = MSRNNumber.substring(2, 4);
   //     SN = Integer.toString(Integer.parseInt(MSRNNumber.substring(4, 12))+1);
   //     cc1.setText(CC);
   //     ndc1.setText(NDC);
   //     sn1.setText(SN);
    //    MSRN = CC+NDC+SN;
        range.setInputVerifier(new RangeVerifier());
        //msrn_no = Integer.getInteger(sn1.getText());
        //System.out.println(MSRNNumber);
        }catch (Exception ex){
            //System.out.println("errorrrrrr");
   //         dbh.insert_first_msrn(MSCName);
        }finally{
  //          MSRNNumber=dbh.get_msrn_no();
  //      CC = MSRNNumber.substring(0, 2);
   //     NDC = MSRNNumber.substring(2, 4);
    //    SN = Long.toString((Long.parseLong(MSRNNumber)+1)).substring(4, 12);
    //    Long new_msrn = Long.parseLong(MSRNNumber)+1;
    //    cc1.setText(CC);
     //   ndc1.setText(NDC);
    //    sn1.setText(SN);
    //    MSRN = CC+NDC+SN;
        range.setInputVerifier(new RangeVerifier());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        submit_comm = new javax.swing.JButton();
        cc1 = new javax.swing.JTextField();
        ndc1 = new javax.swing.JTextField();
        range = new javax.swing.JTextField();
        sn1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        range_lbl = new javax.swing.JLabel();
        from_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setText("MSRN Range:");

        jLabel2.setText("eg:20-10-12345678");

        jLabel19.setText("SN");

        jLabel16.setText("NDC");

        jLabel9.setText("CC");

        jLabel3.setText("From");

        jLabel4.setText("Range of");

        submit_comm.setText("Submit");
        submit_comm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_commActionPerformed(evt);
            }
        });

        cc1.setEnabled(true);
        cc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cc1ActionPerformed(evt);
            }
        });

        ndc1.setEnabled(true);

        sn1.setEnabled(true);

        jLabel5.setText("-");

        jLabel7.setText("-");

        range_lbl.setForeground(new java.awt.Color(44, 39, 97));

        from_lbl.setForeground(new java.awt.Color(21, 22, 87));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(range, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cc1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(submit_comm))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ndc1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(range_lbl)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sn1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(from_lbl))))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(from_lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(range_lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(range, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(ndc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addGap(27, 27, 27)
                        .addComponent(submit_comm)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cc1ActionPerformed

    private void submit_commActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_commActionPerformed

        System.out.println(Integer.parseInt(sn1.getText()));
        
         String msrnstartst = cc1.getText()+ndc1.getText()+sn1.getText();
     //   long msrnstart = Long.parseLong(msrnstartst);
        
       // dbh.insert_msrn(Long.parseLong(MSRNNumber), Integer.parseInt(range.getText()), MSCName);
        dbh.insert_msrn(Long.parseLong(msrnstartst), Integer.parseInt(range.getText()), MSCName);
        
        range.setText("");
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_submit_commActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new msrn_range("msc1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cc1;
    private javax.swing.JLabel from_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField ndc1;
    private javax.swing.JTextField range;
    private javax.swing.JLabel range_lbl;
    private javax.swing.JTextField sn1;
    private javax.swing.JButton submit_comm;
    // End of variables declaration//GEN-END:variables



    public class RangeVerifier extends InputVerifier {

        public boolean verify(JComponent input) {
            range_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                range_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() == 0) {
                range_lbl.setText("Please enter a range");
                check = false;
            }
            return check;
        }
    }

//    public class cc1Verifier extends InputVerifier {
//
//        public boolean verify(JComponent input) {
//            //vlr_lbl.setText("");
//            Boolean check = true;
//            JTextField tf = (JTextField) input;
//            String s = tf.getText();
//
//            if (!Pattern.matches("\\d*$", s)) {
//                from_lbl.setText("must be numeric");
//                check = false;
//            } else if (s.length() != 2) {
//                from_lbl.setText("must be 2 digits");
//                check = false;
//            }
//
//            return check;
//        }
//    }
//
//    public class ndc1Verifier extends InputVerifier {
//
//        public boolean verify(JComponent input) {
//            from_lbl.setText("");
//            Boolean check = true;
//            JTextField tf = (JTextField) input;
//            String s = tf.getText();
//
//            if (!Pattern.matches("\\d*$", s)) {
//                from_lbl.setText("must be numeric");
//                check = false;
//            } else if (s.length() != 2) {
//                from_lbl.setText("must be 2 digits");
//                check = false;
//            }
//
//
//            return check;
//        }
//    }
//
//    public class sn1Verifier extends InputVerifier {
//
//        public boolean verify(JComponent input) {
//            from_lbl.setText("");
//            Boolean check = true;
//            JTextField tf = (JTextField) input;
//            String s = tf.getText();
//
//            if (!Pattern.matches("\\d*$", s)) {
//                from_lbl.setText("must be numeric");
//                check = false;
//            } else if (s.length() != 8) {
//                from_lbl.setText("must be 8 digNewMscits");
//                check = false;
//            }
//            else
//            {
//                String msrn = cc1.getText() + ndc1.getText() + sn1.getText();
//                boolean exist = dbh.check_msc_msrn(msrn);
//                if(exist)
//                {
//                    from_lbl.setText("This MSRN Number already exist");
//                    check = false;
//                }
//            }
//            return check;
//        }
//    }
}
