/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ms_app;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JTextField;

/**
 *
 * @author somaya
 */
public class ms_form extends javax.swing.JFrame
{
    private String simsi1;
    private String simsi2;
    private String simsi3;
    private String smsisdn1;
    private String smsisdn2;
    private String smsisdn3;
    private String la;
    private String msstatus;
    private String slai1;
    private String slai2;
    private String slai3;

    /**
     * Creates new form ms_form
     */
    public ms_form()
    {
        initComponents();
        mcc.setInputVerifier(new mccverifier());
        cc.setInputVerifier(new ccverifier());
        LAmcc.setInputVerifier(new LAmccverifier());
        mnc.setInputVerifier(new mncverifier());
        ndc.setInputVerifier(new ndcverifier());
        LAmnc.setInputVerifier(new LAmncverifier());
        msin.setInputVerifier(new msinverifier());
        sn.setInputVerifier(new snverifier());
        lac.setInputVerifier(new lacverifier());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mcc = new javax.swing.JTextField();
        mnc = new javax.swing.JTextField();
        msin = new javax.swing.JTextField();
        cc = new javax.swing.JTextField();
        ndc = new javax.swing.JTextField();
        sn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LAmcc = new javax.swing.JTextField();
        LAmnc = new javax.swing.JTextField();
        lac = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MS Form");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Mobile Station Form");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("IMSI ");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setText("MSISDN");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setText("LAI ");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mcc.setText("MCC");
        mcc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mccFocusGained(evt);
            }
        });

        mnc.setText("MNC");
        mnc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mncFocusGained(evt);
            }
        });

        msin.setText("                      MSIN");
        msin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msinActionPerformed(evt);
            }
        });
        msin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                msinFocusGained(evt);
            }
        });

        cc.setText("CC");
        cc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ccFocusGained(evt);
            }
        });

        ndc.setText("NDC");
        ndc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ndcFocusGained(evt);
            }
        });

        sn.setText("                        SN");
        sn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                snFocusGained(evt);
            }
        });

        jLabel6.setText("-");

        jLabel7.setText("-");

        jLabel8.setText("-");

        jLabel9.setText("-");

        LAmcc.setText("MCC");
        LAmcc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LAmccFocusGained(evt);
            }
        });

        LAmnc.setText("MNC");
        LAmnc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LAmncFocusGained(evt);
            }
        });

        lac.setText("                       LAC");
        lac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lacFocusGained(evt);
            }
        });

        jLabel10.setText("-");

        jLabel11.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mcc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(LAmcc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LAmnc, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lac, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mnc)
                                    .addComponent(ndc, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sn)
                                    .addComponent(msin, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(302, 302, 302)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ndc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(LAmcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LAmnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /******IMSI String*******/
        simsi1 = mcc.getText();
        simsi2 = mnc.getText();
        simsi3 = msin.getText();
        String imsi = simsi1+simsi2+simsi3;
           
        /******MSISDN String*******/
        smsisdn1 = cc.getText();
        smsisdn2 = ndc.getText();
        smsisdn3 = sn.getText();
        String msisdn = smsisdn1+smsisdn2+smsisdn3;
            
        /******Location Area String*******/
        slai1 = LAmcc.getText();
        slai2 = LAmnc.getText();
        slai3 = lac.getText();
        String lai = slai1+slai2+slai3;
           
        try
        {
            new sendtoerl(imsi, msisdn, lai);
        } catch (Exception ex) {
            Logger.getLogger(ms_form.class.getName()).log(Level.SEVERE, null, ex);
        } 
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void msinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msinActionPerformed

    private void mccFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mccFocusGained
            // TODO add your handling code here:
            mcc.setText("");
    }//GEN-LAST:event_mccFocusGained

    private void mncFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mncFocusGained
        // TODO add your handling code here:
        mnc.setText("");
    }//GEN-LAST:event_mncFocusGained

    private void msinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msinFocusGained
        // TODO add your handling code here:
        msin.setText("");
    }//GEN-LAST:event_msinFocusGained

    private void ccFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ccFocusGained
        cc.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_ccFocusGained

    private void ndcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ndcFocusGained
        // TODO add your handling code here:
        ndc.setText("");
    }//GEN-LAST:event_ndcFocusGained

    private void snFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_snFocusGained
        // TODO add your handling code here:
        sn.setText("");
    }//GEN-LAST:event_snFocusGained

    private void LAmccFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LAmccFocusGained
        // TODO add your handling code here:
        LAmcc.setText("");
    }//GEN-LAST:event_LAmccFocusGained

    private void LAmncFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LAmncFocusGained
        // TODO add your handling code here:
        LAmnc.setText("");
    }//GEN-LAST:event_LAmncFocusGained

    private void lacFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lacFocusGained
        // TODO add your handling code here:
        lac.setText("");
    }//GEN-LAST:event_lacFocusGained
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ms_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ms_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ms_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ms_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        //</editor-fold>

        /*
         * Create and display the form
         */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
          public void run()
          {
            ms_form ms = new ms_form();
            ms.setVisible(true);
            ms.rootPane.setLocation(150,150);
          }
    });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LAmcc;
    private javax.swing.JTextField LAmnc;
    private javax.swing.JTextField cc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lac;
    private javax.swing.JTextField mcc;
    private javax.swing.JTextField mnc;
    private javax.swing.JTextField msin;
    private javax.swing.JTextField ndc;
    private javax.swing.JTextField sn;
    // End of variables declaration//GEN-END:variables

    public static boolean isNumeric(String aStringValue)
    {
        Pattern pattern = Pattern.compile( "\\d+" );
        Matcher matcher = pattern.matcher(aStringValue);
        return matcher.matches();
    }

class mccverifier extends InputVerifier
{
    boolean bool = false;
    public boolean verify(JComponent input)
    {
        JTextField textField = (JTextField) input;
        jLabel15.setText("");
        if(ms_form.isNumeric(textField.getText()))
        {
            if(textField.getText().length() == 3)
            bool = true;
        }
        if(!bool)
        {
            jLabel15.setText("MCC Error");
            textField.setText("");
        }
        return bool;
    }
}

class LAmccverifier extends InputVerifier
{
    boolean bool = false;
    public boolean verify(JComponent input)
    {
        JTextField textField = (JTextField) input;
        jLabel17.setText("");
        if(ms_form.isNumeric(textField.getText()))
        {
            if(textField.getText().length() == 3)
            bool = true;
        }
        if(!bool) {jLabel17.setText(" MCC Error");
        textField.setText("");
    }
    return bool;
    }
}

class mncverifier extends InputVerifier
{
    boolean bool = false;
    public boolean verify(JComponent input)
    {
        JTextField textField = (JTextField) input;
        jLabel15.setText("");
        if(ms_form.isNumeric(textField.getText()))
        {
            if(textField.getText().length() == 2)
            bool = true;
        }
        if(!bool)
        {
            jLabel15.setText(" MNC Error");
            textField.setText("");
        }
        return bool;
    }
}

class LAmncverifier extends InputVerifier
{
    boolean bool = false;
    public boolean verify(JComponent input)
    {
        JTextField textField = (JTextField) input;
        jLabel17.setText("");
        if(ms_form.isNumeric(textField.getText()))
        {
            if(textField.getText().length() == 2)
            bool = true;
        }
        if(!bool)
        {
            jLabel17.setText(" MNC Error");
            textField.setText("");
        }
        return bool;
    }
}


class snverifier extends InputVerifier
{
    boolean bool = false;
    public boolean verify(JComponent input)
    {
        JTextField textField = (JTextField) input;
        jLabel16.setText("");
        if(ms_form.isNumeric(textField.getText()))
        {
            if(textField.getText().length() == 10)
            bool = true;
        }
        if(!bool)
        {
            jLabel16.setText(" SN Error");
            textField.setText("");
        }
        return bool;
    }
}

class lacverifier extends InputVerifier
{
    boolean bool = false;
    public boolean verify(JComponent input)
    {
        JTextField textField = (JTextField) input;
        jLabel17.setText("");
        if(ms_form.isNumeric(textField.getText()))
        {
            int lac = Integer.parseInt(textField.getText());
            bool = true;
        }
        if(!bool)
        {
            jLabel17.setText(" LAC Error");
            textField.setText("");
        }
        return bool;
    }
}

class ndcverifier extends InputVerifier
{
    boolean bool = false;
    public boolean verify(JComponent input)
    {
        JTextField textField = (JTextField) input;
        jLabel16.setText("");
        if(ms_form.isNumeric(textField.getText()))
        {
            if(textField.getText().length() == 2 ||textField.getText().length() == 3 )
            bool = true;
        }
        if(!bool)
        {
            jLabel16.setText("NDC Error");
            textField.setText("");
        }
        return bool;
    }
}

class ccverifier extends InputVerifier
{
    boolean bool = false;
    public boolean verify(JComponent input)
    {
        JTextField textField = (JTextField) input;
        jLabel16.setText("");
        if(ms_form.isNumeric(textField.getText()))
        {
            if(textField.getText().length() == 2 ||textField.getText().length() == 3 )
            bool = true;
        }
        if(!bool)
        {
            jLabel16.setText(" CC Error");
            textField.setText("");
        }
        return bool;
    }
}

class msinverifier extends InputVerifier
{
    boolean bool = false;
    public boolean verify(JComponent input)
    {
        JTextField textField = (JTextField) input;
        jLabel15.setText("");
        if(ms_form.isNumeric(textField.getText()))
        {
            if(textField.getText().length() == 10)
            bool = true;
            jLabel15.setText("");
        }
     if(!bool)
     {
         jLabel15.setText(" MSIN Error");
         textField.setText("");
     }
     return bool;
    }
}

}
