/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Msc_Screen.java
 *
 * Created on Jun 10, 2012, 1:44:30 PM
 */
package msc;

import com.ericsson.otp.erlang.OtpErlangAtom;
import com.ericsson.otp.erlang.OtpErlangObject;
import com.ericsson.otp.erlang.OtpErlangTuple;
import com.iti.telecom.beans.MSC;
import com.iti.telecom.editor.BasicGraphEditor;
import com.mxgraph.model.mxCell;
import com.mxgraph.view.mxGraph;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Vendetta
 */
public class Msc_Screen extends JDialog {

    private JFrame parent = null;
    private mxGraph graph;
    private mxCell cell;
    private BasicGraphEditor editor;
    MSC msc;
    boolean lai_enable;
    public static DatabaseHandler dbh;
    boolean namef = false, nif = false, spcf = false, ccf = false, ndcf = false, snf = false, cc2f = false, ndc2f = false, snf2f = false;

    //static int flag_insert = 0;   //for insert in first time and update in second time
    
    /**
     * Creates new form Msc_Screen
     */
    public Msc_Screen(JFrame parent, BasicGraphEditor editor, Object cell, mxGraph graph, mxCell agentsCell) {
        super(parent);
        initComponents();
        dbh = new DatabaseHandler();

        msc = new MSC();

        this.parent = parent;
        this.editor = editor;
        this.graph = graph;
        this.cell = agentsCell;
        this.msc = (MSC) cell;

        msc_name.setInputVerifier(new NameVerifier());

        NI_num.setInputVerifier(new NIVerifier());
        SPC_num.setInputVerifier(new SPCVerifier());

        gt1.setInputVerifier(new GT1Verifier());
        gt2.setInputVerifier(new GT2Verifier());
        gt3.setInputVerifier(new GT3Verifier());
        /*
         * LA_id1.setInputVerifier(new LA1Verifier());
         * LA_id2.setInputVerifier(new LA2Verifier());
         * LA_id3.setInputVerifier(new LA3Verifier());
         */
        VLR_add1.setInputVerifier(new VLR1Verifier());
        VLR_add2.setInputVerifier(new VLR2Verifier());
        VLR_add3.setInputVerifier(new VLR3Verifier());
        getCellProperties();
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Submit_comm = new javax.swing.JButton();
        NI_num = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gt1 = new javax.swing.JTextField();
        SPC_num = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        VLR_add1 = new javax.swing.JTextField();
        msc_name = new javax.swing.JTextField();
        gt_lbl = new javax.swing.JLabel();
        ni_lbl = new javax.swing.JLabel();
        vlr_lbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        VLR_add2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        VLR_add3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        gt2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        gt3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Submit_comm.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Submit_comm.setText("Submit");
        Submit_comm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_commActionPerformed(evt);
            }
        });

        NI_num.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        NI_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NI_numActionPerformed(evt);
            }
        });
        NI_num.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NI_numFocusGained(evt);
            }
        });

        jLabel7.setText("-");

        gt1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        gt1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gt1FocusGained(evt);
            }
        });

        SPC_num.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        SPC_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPC_numActionPerformed(evt);
            }
        });
        SPC_num.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SPC_numFocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("VLR:");

        jLabel1.setBackground(new java.awt.Color(250, 254, 254));
        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(19, 7, 101));
        jLabel1.setText("MSC Configuration");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("GT:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("NI-SPC:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Name:");

        VLR_add1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        VLR_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VLR_add1ActionPerformed(evt);
            }
        });
        VLR_add1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                VLR_add1FocusGained(evt);
            }
        });

        msc_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msc_nameActionPerformed(evt);
            }
        });
        msc_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                msc_nameFocusGained(evt);
            }
        });

        gt_lbl.setForeground(new java.awt.Color(24, 25, 61));
        gt_lbl.setText("ex: 20 - 10 - 1234567890");

        ni_lbl.setForeground(new java.awt.Color(24, 25, 61));
        ni_lbl.setText("ex: (0 or 2 or 3) - (1 – 65535)");

        vlr_lbl.setForeground(new java.awt.Color(24, 25, 61));
        vlr_lbl.setText("ex: 20 - 10 - 1234567890");

        jLabel11.setForeground(new java.awt.Color(250, 65, 16));

        name_lbl.setForeground(new java.awt.Color(24, 25, 61));
        name_lbl.setText("1 - 7 digits");

        VLR_add2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        VLR_add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VLR_add2ActionPerformed(evt);
            }
        });
        VLR_add2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                VLR_add2FocusGained(evt);
            }
        });

        jLabel10.setText("-");

        VLR_add3.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        VLR_add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VLR_add3ActionPerformed(evt);
            }
        });
        VLR_add3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                VLR_add3FocusGained(evt);
            }
        });

        jLabel12.setText("-");

        gt2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        gt2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gt2FocusGained(evt);
            }
        });

        jLabel13.setText("-");

        gt3.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        gt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gt3ActionPerformed(evt);
            }
        });
        gt3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gt3FocusGained(evt);
            }
        });

        jLabel14.setText("-");

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setText("GT-Translation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton2.setText("new LAI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("CC");

        jLabel9.setText("CC");

        jLabel15.setText("NDC");

        jLabel16.setText("NDC");

        jLabel17.setText("NI");

        jLabel18.setText("SPC");

        jLabel19.setText("SN");

        jLabel20.setText("SN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 67, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(254, 254, 254))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(NI_num, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(12, 12, 12)
                                                    .addComponent(jLabel9)))
                                            .addGap(14, 14, 14)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(5, 5, 5)
                                                            .addComponent(SPC_num))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jLabel16)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabel19)
                                                            .addGap(55, 55, 55))))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel14)
                                                    .addGap(5, 5, 5)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(gt2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jLabel13)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(gt3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(12, 12, 12)
                                                            .addComponent(jLabel15)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabel20)
                                                            .addGap(51, 51, 51))))))
                                        .addComponent(msc_name, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(jLabel17)
                                            .addGap(56, 56, 56)
                                            .addComponent(jLabel18)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(VLR_add1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel8))
                                            .addComponent(gt1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(VLR_add2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(VLR_add3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vlr_lbl)
                                    .addComponent(gt_lbl)
                                    .addComponent(ni_lbl)
                                    .addComponent(name_lbl)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton1)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(Submit_comm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(msc_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SPC_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(NI_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ni_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gt_lbl)
                    .addComponent(gt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(gt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VLR_add1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vlr_lbl)
                    .addComponent(jLabel12)
                    .addComponent(VLR_add2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VLR_add3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addGap(34, 34, 34)
                .addComponent(Submit_comm)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit_commActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_commActionPerformed


        //if (namef && nif && spcf && ccf && ndcf && snf && cc2f && ndc2f && snf2f) 
        //{
        String NI_SPC = NI_num.getText() + SPC_num.getText();
        String GT = gt1.getText() + gt2.getText() + gt3.getText();
        String VLR = VLR_add1.getText() + VLR_add2.getText() + VLR_add3.getText();
            
        if(msc_name.getText().equals("") || VLR.equals(""))
        {
            jLabel4.setText("You must insert at least MSC name and VLR address");
        }
        else
        {
            jLabel4.setText("");
        if(msc.getVisited() == 0)
        {
            boolean exist = dbh.check_msc_name_vlr(msc_name.getText(), VLR);
            System.out.println("EXISSSSSSST: "+ exist);
            if(exist)
            {
                jLabel4.setText("This MSC and/or VLR address already defined");
            }
            else
            {
                jLabel4.setText("");
                dbh.insert_msc_info(msc_name.getText(), NI_num.getText(), SPC_num.getText(), GT, VLR);
                msc.setVisited(1);

                OtpErlangAtom atom2 = new OtpErlangAtom(msc.getMscName());

                OtpErlangObject[] ob = new OtpErlangObject[1];
                ob[0] = atom2;
                try {
                    //      send_to_erl.sendtoerl2 sender = new send_to_erl.sendtoerl2();
                    System.out.println("array " + ob[0].toString());
                    com.iti.telecom.main.GraphEditor.sender.sendtoerl("newmsc", ob);

                    jButton2.setEnabled(true);
                    jButton1.setEnabled(true);
                    msc.setlai_enabel(true);

                } catch (Exception ex) {
                    Logger.getLogger(Msc_Screen.class.getName()).log(Level.SEVERE, null, ex);
                }


            }
        }
            else
            {
                dbh.update_msc_info(msc_name.getText(), NI_num.getText(), SPC_num.getText(), GT, VLR);
                msc.setMscName(msc_name.getText());
                msc.setVlrAdd1(VLR_add1.getText());
            msc.setVlrAdd2(VLR_add2.getText());
            msc.setVlrAdd3(VLR_add3.getText());

            NI_num.setFocusable(true);
                msc_name.setEditable(false);
                VLR_add1.setEditable(false);
                VLR_add2.setEditable(false);
                VLR_add3.setEditable(false);
            }
            
            msc.setMscName(msc_name.getText());
            
            msc.setNi(NI_num.getText());
            msc.setSpc(SPC_num.getText());
            
            msc.setGt1(gt1.getText());
            msc.setGt2(gt2.getText());
            msc.setGt3(gt3.getText());

            msc.setVlrAdd1(VLR_add1.getText());
            msc.setVlrAdd2(VLR_add2.getText());
            msc.setVlrAdd3(VLR_add3.getText());


            
        //} else {
          //  jLabel4.setText("insert all fields");
        //}
            }

}//GEN-LAST:event_Submit_commActionPerformed

    private void NI_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NI_numActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_NI_numActionPerformed

    private void SPC_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPC_numActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_SPC_numActionPerformed

    private void VLR_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VLR_add1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_VLR_add1ActionPerformed

    private void msc_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msc_nameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_msc_nameActionPerformed

    private void VLR_add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VLR_add3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VLR_add3ActionPerformed

    private void gt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gt3ActionPerformed

    private void NI_numFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NI_numFocusGained
        // TODO add your handling code here:
nif=true;
        //NI_num.setText("");
        ni_lbl.setText("ex: (0 or 2 or 3) - (1 – 65535)");
    }//GEN-LAST:event_NI_numFocusGained

    private void SPC_numFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SPC_numFocusGained
        // TODO add your handling code here:
spcf=true;
        //SPC_num.setText("");
        ni_lbl.setText("ex: (0 or 2 or 3) - (1 – 65535)");
    }//GEN-LAST:event_SPC_numFocusGained

    private void gt1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gt1FocusGained
        // TODO add your handling code here:
ccf=true;
        //gt1.setText("");
        gt_lbl.setText("ex: 20 - 10 - 1234567890");
    }//GEN-LAST:event_gt1FocusGained

    private void gt2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gt2FocusGained
        // TODO add your handling code here:
ndcf=true;
        //gt2.setText("");
        gt_lbl.setText("ex: 20 - 10 - 1234567890");
    }//GEN-LAST:event_gt2FocusGained

    private void gt3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gt3FocusGained
        // TODO add your handling code here:
snf=true;
        //gt3.setText("");
        gt_lbl.setText("ex: 20 - 10 - 1234567890");
    }//GEN-LAST:event_gt3FocusGained

    private void VLR_add1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_VLR_add1FocusGained
        // TODO add your handling code here:
cc2f=true;
        //VLR_add1.setText("");
        vlr_lbl.setText("ex: 20 - 10 - 1234567890");
    }//GEN-LAST:event_VLR_add1FocusGained

    private void VLR_add2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_VLR_add2FocusGained
        // TODO add your handling code here:
ndc2f=true;
       // VLR_add2.setText("");
        vlr_lbl.setText("ex: 20 - 10 - 1234567890");
    }//GEN-LAST:event_VLR_add2FocusGained

    private void VLR_add3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_VLR_add3FocusGained
        // TODO add your handling code here:
snf2f=true;
        //VLR_add3.setText("");
        vlr_lbl.setText("ex: 20 - 10 - 1234567890");
    }//GEN-LAST:event_VLR_add3FocusGained

    private void msc_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msc_nameFocusGained
        // TODO add your handling code here:
        namef = true;
        //msc_name.setText("");
        name_lbl.setText("1 - 7 digits");
    }//GEN-LAST:event_msc_nameFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String VLR = VLR_add1.getText() + VLR_add2.getText() + VLR_add3.getText();
        System.out.println("NAAAMEEe  :" + msc_name.getText()+VLR);
        GT_translation screen = new GT_translation(msc_name.getText(), VLR);
        //screen.setSize(700, 400);
        screen.setVisible(true);
       
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String vlradd = msc.getVlrAdd1() + msc.getVlrAdd2() + msc.getVlrAdd3();
        lai_conf lai_forum = new lai_conf(msc.getMscName(), vlradd);

        lai_forum.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void VLR_add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VLR_add2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VLR_add2ActionPerformed
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new Msc_Screen().setVisible(true);
//            }
//        });
//
//
//
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NI_num;
    private javax.swing.JTextField SPC_num;
    private javax.swing.JButton Submit_comm;
    private javax.swing.JTextField VLR_add1;
    private javax.swing.JTextField VLR_add2;
    private javax.swing.JTextField VLR_add3;
    private javax.swing.JTextField gt1;
    private javax.swing.JTextField gt2;
    private javax.swing.JTextField gt3;
    private javax.swing.JLabel gt_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField msc_name;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JLabel ni_lbl;
    private javax.swing.JLabel vlr_lbl;
    // End of variables declaration//GEN-END:variables

    private void getCellProperties() {
        msc_name.setText(msc.getMscName());
        NI_num.setText(msc.getNi());
        SPC_num.setText(msc.getSpc());
        gt1.setText(msc.getGt1());
        gt2.setText(msc.getGt2());
        gt3.setText(msc.getGt3());
        VLR_add1.setText(msc.getVlrAdd1());
        VLR_add2.setText(msc.getVlrAdd2());
        VLR_add3.setText(msc.getVlrAdd3());
//        LA_id1.setText(msc.getLa1());
        //      LA_id2.setText(msc.getLa2());
        //      LA_id3.setText(msc.getLa3());

        jButton2.setEnabled(msc.getlai_enabel());
        jButton1.setEnabled(msc.getlai_enabel());
        //Submit_comm.setEnabled(!msc.getlai_enabel());


        /*msc_name.setEnabled(!msc.getlai_enabel());
        NI_num.setEnabled(!msc.getlai_enabel());
        SPC_num.setEnabled(!msc.getlai_enabel());
        VLR_add1.setEnabled(!msc.getlai_enabel());
        VLR_add2.setEnabled(!msc.getlai_enabel());
        VLR_add3.setEnabled(!msc.getlai_enabel());
        gt1.setEnabled(!msc.getlai_enabel());
        gt2.setEnabled(!msc.getlai_enabel());
        gt3.setEnabled(!msc.getlai_enabel());*/
        
        //if(flag_insert == 1)
        //{
            System.out.println("AAAAAAAAAAAAAAAAAAAT ");
            msc_name.setEnabled(!msc.getlai_enabel());
            VLR_add1.setEnabled(!msc.getlai_enabel());
            VLR_add2.setEnabled(!msc.getlai_enabel());
            VLR_add3.setEnabled(!msc.getlai_enabel());
        //}
    }
    // End of variables declaration

    public class NameVerifier extends InputVerifier {

        public boolean verify(JComponent input) {
            
            
            name_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();
            if (s.length() == 0) {
                //JOptionPane.showMessageDialog( null , "Name is empty ");
                //name_lbl.setVisible(true);
                name_lbl.setText("Name is empty");
                check = false;
            } else if (s.length() > 7) {
                JOptionPane.showMessageDialog(null, "Name must be less than 7 digits ");
                name_lbl.setText("1-7 digits are required");
                check = false;
            }
            else
            {
                boolean exist = dbh.check_msc_name(msc_name.getText());
                if(exist)
                {
                    name_lbl.setText("This name already exist");
                    check = false;
                }
                
                
            }
            return check;
        }
    }

    public class NIVerifier extends InputVerifier {

        public boolean verify(JComponent input) {


            ni_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                ni_lbl.setText("NI isn't numeric");
                check = false;
            }
            if (s.length() == 0) {
                //JOptionPane.showMessageDialog( null , "Name is empty ");
                ni_lbl.setText("NI is empty");
                check = false;
            } else if (!s.equals("0") && !s.equals("2") && !s.equals("3")) {
                //JOptionPane.showMessageDialog( null , "Name must be less than 3 digits ");
                ni_lbl.setText("0 or 2 or 3 is required");
                check = false;
            }
            
            return check;
        }
    }

    public class SPCVerifier extends InputVerifier {

        public boolean verify(JComponent input) {
            ni_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            
            String s = tf.getText();
            int num = Integer.parseInt(s);
            if (!Pattern.matches("\\d*$", s)) {
                ni_lbl.setText("SPC isn't numeric");
                check = false;
            }
            if (s.length() == 0) {
                //JOptionPane.showMessageDialog( null , "Name is empty ");
                ni_lbl.setText("SPC is empty");
                check = false;
            } else if (num < 1 || num > 65535) {
                //JOptionPane.showMessageDialog( null , "Name must be less than 14 digits ");
                ni_lbl.setText("must be in range 1 - 65535");
                check = false;
            }
            else
            {
                String ni_spc = NI_num.getText() + SPC_num.getText();
                boolean exist = dbh.check_msc_ni_spc(ni_spc);
                if(exist)
                {
                    ni_lbl.setText("This NI_SPC already exist");
                    check = false;
                }
                
            }

            return check;
          
        }
    }

    public class GT1Verifier extends InputVerifier {

        public boolean verify(JComponent input) {
            gt_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                gt_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() != 2) {
                gt_lbl.setText("must be 2 digits");
                check = false;
            }
            return check;
        }
    }

    public class GT2Verifier extends InputVerifier {

        public boolean verify(JComponent input) {
            gt_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                gt_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() != 2) {
                gt_lbl.setText("must be 2 digits");
                check = false;
            }

            return check;
        }
    }

    public class GT3Verifier extends InputVerifier {

        public boolean verify(JComponent input) {
            gt_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                gt_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() != 10) {
                gt_lbl.setText("must be 10 digits");
                check = false;
            }
            else
            {
                String gt = gt1.getText() + gt2.getText() + gt3.getText();
                boolean exist = dbh.check_msc_gt(gt);
                if(exist)
                {
                    gt_lbl.setText("This GT already exist");
                    check = false;
                }
                
            }
            return check;
        }
    }
    /*
     * public class LA1Verifier extends InputVerifier {
     *
     * public boolean verify(JComponent input) { la_lbl.setText(""); Boolean
     * check = true; JTextField tf = (JTextField) input; String s =
     * tf.getText();
     *
     * if (!Pattern.matches("\\d*$", s)) { la_lbl.setText("must be numeric");
     * check = false; } else if (s.length() != 3) { la_lbl.setText("must be 3
     * digits"); check = false; }
     *
     * return check; } }
     *
     * public class LA2Verifier extends InputVerifier {
     *
     * public boolean verify(JComponent input) { la_lbl.setText(""); Boolean
     * check = true; JTextField tf = (JTextField) input; String s =
     * tf.getText();
     *
     * if (!Pattern.matches("\\d*$", s)) { la_lbl.setText("must be numeric");
     * check = false; } else if (s.length() != 2) { la_lbl.setText("must be 2
     * digits"); check = false; }
     *
     * return check; } }
     *
     * public class LA3Verifier extends InputVerifier {
     *
     * public boolean verify(JComponent input) { la_lbl.setText(""); Boolean
     * check = true; JTextField tf = (JTextField) input; String s =
     * tf.getText();
     *
     * if (!Pattern.matches("\\d*$", s)) { la_lbl.setText("must be numeric");
     * check = false; } else if (s.length() != 10) { la_lbl.setText("must be 10
     * digits"); check = false; }
     *
     * return check; }
    }
     */

    public class VLR1Verifier extends InputVerifier {

        public boolean verify(JComponent input) {
            vlr_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                vlr_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() != 2) {
                vlr_lbl.setText("must be 2 digits");
                check = false;
            }

            return check;
        }
    }

    public class VLR2Verifier extends InputVerifier {

        public boolean verify(JComponent input) {
            vlr_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                vlr_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() != 2) {
                vlr_lbl.setText("must be 2 digits");
                check = false;
            }


            return check;
        }
    }

    public class VLR3Verifier extends InputVerifier {

        public boolean verify(JComponent input) {
            vlr_lbl.setText("");
            Boolean check = true;
            JTextField tf = (JTextField) input;
            String s = tf.getText();

            if (!Pattern.matches("\\d*$", s)) {
                vlr_lbl.setText("must be numeric");
                check = false;
            } else if (s.length() != 10) {
                vlr_lbl.setText("must be 10 digNewMscits");
                check = false;
            }
            else
            {
                String vlr = VLR_add1.getText() + VLR_add2.getText() + VLR_add3.getText();
                boolean exist = dbh.check_msc_vlr(vlr);
                if(exist)
                {
                    vlr_lbl.setText("This VLR address already exist");
                    check = false;
                }    
            }
            return check;
        }
    }
}
